name: hybridX push process
on:
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        env:
          NODE_ENV: development
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Create env file
        run: |
          echo VUE_APP_JSON_SERVER=https://jsonplaceholder.typicode.com/blogs >> .env
          echo ${{ secrets.ENV_FILE }} >> .env
          cat .env
      - run: npm install
      - run: npm run build
      - name: Deploy Gamedoora-UI
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{ secrets.GAMEDOORA_DEV }}
          BRANCH: gh-pages
          FOLDER: dist
